version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    target_branch: "develop"
    default_labels:
      - "bot"
    commit_message:
      prefix: "⬆️"
