name: Changelog Generator
on:
  # Trigger the workflow on pull request,
  # but only for the master branch
  pull_request:
    branches:
      - master
    types: [opened, reopened, synchronize]

jobs:
  changelog:
    # Job name is Chanegelog
    name: Chanegelog Generator
    # This job runs on  Linux
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: homeday-de/github-action-changelog-generator@v1.0.0
          with:
            token: ${{ secrets.GITHUB_TOKEN }}